steps:
  # 第一步: 构建 Docker 镜像
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/ddp-ai:$COMMIT_SHA', '.']

  # 第二步: 推送镜像到 Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/ddp-ai:$COMMIT_SHA']

  # 第三步: 部署到 Google Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
    - 'run'
    - 'deploy'
    - 'ddp-ai'
    - '--image'
    - 'gcr.io/$PROJECT_ID/ddp-ai:$COMMIT_SHA'
    - '--region'
    - 'australia-southeast1'  # 选择适合的区域
    - '--platform'
    - 'managed'
    - '--allow-unauthenticated'

images:
  - 'gcr.io/$PROJECT_ID/ddp-ai:$COMMIT_SHA'
